name: Build and Push to GCR

on:
  push:
    tags:
      - v*

env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  IMAGE: tb-api
  PROJECT_NAME: ${{ secrets.GCLOUD_PROJECT_NAME }}
  REGISTRY_HOSTNAME: gcr.io
  ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: |
          ./decryptSecrets.sh

      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCLOUD_SECRET }}
          project_id: ${{ secrets.GCLOUD_PROJECT_NAME }}

      - run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          echo $TAG
          docker build -t "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$IMAGE":"$TAG" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .

      - name: Publish
        run: |
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
          echo $TAG
          docker push "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$IMAGE":"$TAG"
          docker tag "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$IMAGE":"$TAG" "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$IMAGE":latest
          docker push "$REGISTRY_HOSTNAME"/"$PROJECT_NAME"/"$IMAGE":latest
